=== fungiboletus/XMLGallery2011/GalML.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT gallery (file*) >
<!ATTLIST gallery name CDATA #IMPLIED >

<!ELEMENT file (path, mimetype?, size, date, tags)>
<!ATTLIST file name CDATA #REQUIRED >

<!ELEMENT path (#PCDATA) >
<!ELEMENT mimetype (#PCDATA) >
<!ELEMENT size (#PCDATA) >
<!ELEMENT date (#PCDATA) >

<!ELEMENT tags (tag*) >
<!ELEMENT tag EMPTY >
<!ATTLIST tag name CDATA #REQUIRED >

=== fungiboletus/XMLGallery2011/Generated_sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="GalML.xsl"?>
<!DOCTYPE gallery SYSTEM "GalML.dtd">
<gallery name="Miles Davis">
	<file name="01 - Tutu.flac">
		<path>Miles Davis/Tutu/01 - Tutu.flac</path>
		<mimetype>audio/x-flac</mimetype>
		<size>32039431</size>
		<date>2011-02-12 11:34:24.000000000 +0100</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="Tutu" />
		</tags>
	</file>
	<file name="02 - Tomaas.flac">
		<path>Miles Davis/Tutu/02 - Tomaas.flac</path>
		<mimetype>audio/x-flac</mimetype>
		<size>36269960</size>
		<date>2011-02-12 11:34:26.000000000 +0100</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="Tutu" />
		</tags>
	</file>
	<file name="03 - Portia.flac">
		<path>Miles Davis/Tutu/03 - Portia.flac</path>
		<mimetype>audio/x-flac</mimetype>
		<size>38243039</size>
		<date>2011-02-12 11:34:28.000000000 +0100</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="Tutu" />
		</tags>
	</file>
	<file name="04 - Splatch.flac">
		<path>Miles Davis/Tutu/04 - Splatch.flac</path>
		<mimetype>audio/x-flac</mimetype>
		<size>29909271</size>
		<date>2011-02-12 11:34:28.000000000 +0100</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="Tutu" />
		</tags>
	</file>
	<file name="05 - Backyard Ritual.flac">
		<path>Miles Davis/Tutu/05 - Backyard Ritual.flac</path>
		<mimetype>audio/x-flac</mimetype>
		<size>30146030</size>
		<date>2011-02-12 11:34:30.000000000 +0100</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="Tutu" />
		</tags>
	</file>
	<file name="06 - Perfect Way.flac">
		<path>Miles Davis/Tutu/06 - Perfect Way.flac</path>
		<mimetype>audio/x-flac</mimetype>
		<size>28659460</size>
		<date>2011-02-12 11:34:32.000000000 +0100</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="Tutu" />
		</tags>
	</file>
	<file name="07 - Don't Lose Your Mind.flac">
		<path>Miles Davis/Tutu/07 - Don't Lose Your Mind.flac</path>
		<mimetype>audio/x-flac</mimetype>
		<size>35209242</size>
		<date>2011-02-12 11:34:32.000000000 +0100</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="Tutu" />
		</tags>
	</file>
	<file name="08 - Full Nelson.flac">
		<path>Miles Davis/Tutu/08 - Full Nelson.flac</path>
		<mimetype>audio/x-flac</mimetype>
		<size>28654450</size>
		<date>2011-02-12 11:34:34.000000000 +0100</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="Tutu" />
		</tags>
	</file>
	<file name="01 Jean Pierre.flac">
		<path>Miles Davis/We Want Miles/Disc 1/01 Jean Pierre.flac</path>
		<mimetype>audio/x-flac</mimetype>
		<size>75587047</size>
		<date>2010-04-01 01:00:09.000000000 +0200</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="We Want Miles" />
			<tag name="Disc 1" />
		</tags>
	</file>
	<file name="02 Back Seat Betty.flac">
		<path>Miles Davis/We Want Miles/Disc 1/02 Back Seat Betty.flac</path>
		<mimetype>audio/x-flac</mimetype>
		<size>59033521</size>
		<date>2010-04-01 00:47:21.000000000 +0200</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="We Want Miles" />
			<tag name="Disc 1" />
		</tags>
	</file>
	<file name="03 Fast Track.flac">
		<path>Miles Davis/We Want Miles/Disc 1/03 Fast Track.flac</path>
		<mimetype>audio/x-flac</mimetype>
		<size>111104805</size>
		<date>2010-04-01 01:00:40.000000000 +0200</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="We Want Miles" />
			<tag name="Disc 1" />
		</tags>
	</file>
	<file name="04 Jean Pierre.flac">
		<path>Miles Davis/We Want Miles/Disc 1/04 Jean Pierre.flac</path>
		<mimetype>audio/x-flac</mimetype>
		<size>26776982</size>
		<date>2010-03-31 23:03:28.000000000 +0200</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="We Want Miles" />
			<tag name="Disc 1" />
		</tags>
	</file>
	<file name="05 Ursula.flac">
		<path>Miles Davis/We Want Miles/Disc 1/05 Ursula.flac</path>
		<mimetype>audio/x-flac</mimetype>
		<size>13011665</size>
		<date>2010-03-31 23:28:23.000000000 +0200</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="We Want Miles" />
			<tag name="Disc 1" />
		</tags>
	</file>
	<file name="06 Aida.flac">
		<path>Miles Davis/We Want Miles/Disc 1/06 Aida.flac</path>
		<mimetype>audio/x-flac</mimetype>
		<size>84236624</size>
		<date>2010-03-31 21:19:56.000000000 +0200</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="We Want Miles" />
			<tag name="Disc 1" />
		</tags>
	</file>
	<file name="Folder.jpg">
		<path>Miles Davis/We Want Miles/Disc 1/Folder.jpg</path>
		<mimetype>image/jpeg</mimetype>
		<size>237259</size>
		<date>2010-03-31 14:48:00.000000000 +0200</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="We Want Miles" />
			<tag name="Disc 1" />
		</tags>
	</file>
	<file name="We Want Miles (Disc 1).cue">
		<path>Miles Davis/We Want Miles/Disc 1/We Want Miles (Disc 1).cue</path>
		<mimetype>text/plain</mimetype>
		<size>799</size>
		<date>2010-03-31 21:11:10.000000000 +0200</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="We Want Miles" />
			<tag name="Disc 1" />
		</tags>
	</file>
	<file name="We Want Miles (Disc 1).log">
		<path>Miles Davis/We Want Miles/Disc 1/We Want Miles (Disc 1).log</path>
		<mimetype>text/plain</mimetype>
		<size>6033</size>
		<date>2010-03-31 21:11:10.000000000 +0200</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="We Want Miles" />
			<tag name="Disc 1" />
		</tags>
	</file>
	<file name="01 My Man's Gone Now.flac">
		<path>Miles Davis/We Want Miles/Disc 2/01 My Man's Gone Now.flac</path>
		<mimetype>audio/x-flac</mimetype>
		<size>144628204</size>
		<date>2010-03-31 23:38:17.000000000 +0200</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="We Want Miles" />
			<tag name="Disc 2" />
		</tags>
	</file>
	<file name="02 Kix.flac">
		<path>Miles Davis/We Want Miles/Disc 2/02 Kix.flac</path>
		<mimetype>audio/x-flac</mimetype>
		<size>139452101</size>
		<date>2010-04-01 00:59:13.000000000 +0200</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="We Want Miles" />
			<tag name="Disc 2" />
		</tags>
	</file>
	<file name="03 Fat Time.flac">
		<path>Miles Davis/We Want Miles/Disc 2/03 Fat Time.flac</path>
		<mimetype>audio/x-flac</mimetype>
		<size>87146434</size>
		<date>2010-04-01 00:55:16.000000000 +0200</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="We Want Miles" />
			<tag name="Disc 2" />
		</tags>
	</file>
	<file name="Folder.jpg">
		<path>Miles Davis/We Want Miles/Disc 2/Folder.jpg</path>
		<mimetype>image/jpeg</mimetype>
		<size>237259</size>
		<date>2010-03-31 14:48:00.000000000 +0200</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="We Want Miles" />
			<tag name="Disc 2" />
		</tags>
	</file>
	<file name="We Want Miles (Disc 2).cue">
		<path>Miles Davis/We Want Miles/Disc 2/We Want Miles (Disc 2).cue</path>
		<mimetype>text/plain</mimetype>
		<size>437</size>
		<date>2010-03-31 22:15:51.000000000 +0200</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="We Want Miles" />
			<tag name="Disc 2" />
		</tags>
	</file>
	<file name="We Want Miles (Disc 2).log">
		<path>Miles Davis/We Want Miles/Disc 2/We Want Miles (Disc 2).log</path>
		<mimetype>text/plain</mimetype>
		<size>3361</size>
		<date>2010-03-31 22:15:51.000000000 +0200</date>
		<tags>
			<tag name="Miles Davis" />
			<tag name="We Want Miles" />
			<tag name="Disc 2" />
		</tags>
	</file>
</gallery>

=== fungiboletus/XMLGallery2011/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="GalML.xsl"?>
<!DOCTYPE gallery SYSTEM "GalML.dtd">
<gallery name="Galerie d'exemple">
	<file name="Le plus beau jour du monde">
		<path>plusbeaujour.avi</path>
		<mimetype>text/plain</mimetype>
		<size>5445</size>
		<date>50 Janvier 2011</date>
		<tags>
			<tag name="video" />
			<tag name="interessant" />
			<tag name="super" />
		</tags>
	</file>
	<file name="I prefer your clone">
		<path>musics/iprefer.mp3</path>
		<mimetype>audio/mpeg</mimetype>
		<size>544554</size>
		<date>12 Février 2031</date>
		<tags>
			<tag name="musique" />
			<tag name="hadopi" />
			<tag name="soupe horrible" />
			<tag name="génial" />
		</tags>
	</file>
	<file name="Ce beau fichier">
		<path>sample.xml</path>
		<mimetype>application/xml</mimetype>
		<size>1452</size>
		<date>23 Octobre 2011</date>
		<tags>
			<tag name="exemples" />
			<tag name="génial" />
		</tags>
	</file>
</gallery>
